platform :ios, '14.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

flipper_config = FlipperConfiguration.disabled

target 'RnTest' do
  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Lookin
  pod 'LookinServer', :configurations => ['Debug']

  target 'RnTestTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end
